name: security_app
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1

  gap: ^3.0.1
  iconsax: ^0.0.8
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_native_splash: ^2.4.1
  curved_navigation_bar: ^1.0.6

  intl: 0.19.0
  http: ^1.1.2
  logger: ^2.5.0
  url_launcher: ^6.2.4
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.5
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  flutter_secure_storage: ^9.2.2

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/lottie/misc/
    - assets/images/misc/
    - assets/logos/

